module.exports = [
  {
    "key": "color",
    "zh": "调色",
    "en": "Color",
    "es": "Color",
    "de": "Tinting",
    "ja": "いろあわせ",
    "ru": "Цветовая настройка",
    "fr": "Tonifier la couleur",
    "pt": "Paleta de cores",
    "uk": "Колір",
    "nl": "Kleurpalet",
    "ko": "색상"
  },
  {
    "key": "effect",
    "zh": "效果",
    "en": "Effect",
    "es": "Influencia",
    "de": "Wirkung",
    "ja": "効果＃コウカ＃",
    "ru": "Эффект",
    "fr": "Effets",
    "pt": "efeito",
    "uk": "Ефект",
    "nl": "effect",
    "ko": "효과"
  },
  {
    "key": "music.0",
    "zh": "经典",
    "en": "Classic",
    "es": "Clásico",
    "de": "Klassisch",
    "ja": "クラシック",
    "ru": "Классика",
    "fr": "classique",
    "pt": "Clássico",
    "uk": "Класичний",
    "nl": "klassiek",
    "ko": "고전"
  },
  {
    "key": "music.1",
    "zh": "柔和",
    "en": "Soft",
    "es": "Suave",
    "de": "weich",
    "ja": "ストレッチ",
    "ru": "Растянуть",
    "fr": "doux",
    "pt": "Estique",
    "uk": "Розтягнути",
    "nl": "zacht",
    "ko": "소프트"
  },
  {
    "key": "music.2",
    "zh": "动感",
    "en": "Sport",
    "es": "Dinámica",
    "de": "Dynamisch",
    "ja": "スポーツ",
    "ru": "Динамично",
    "fr": "Sport",
    "pt": "Desporto",
    "uk": "Спорт",
    "nl": "Dynamisch",
    "ko": "운동"
  },
  {
    "key": "music.3",
    "zh": "迪斯科",
    "en": "Disco",
    "es": "Disco",
    "de": "Disco",
    "ja": "ディスコ",
    "ru": "Диски",
    "fr": "Disco",
    "pt": "Disco.",
    "uk": "Диско",
    "nl": "disco",
    "ko": "디스코"
  },
  {
    "key": "music.sensitivity",
    "zh": "灵敏度",
    "en": "Sensitivity:",
    "es": "Sensibilidad",
    "de": "Empfindlichkeit",
    "ja": "感度:",
    "ru": "Чувствительность:",
    "fr": "Sensibilité",
    "pt": "Sensibilidade:",
    "uk": "Чутливість:",
    "nl": "gevoeligheid",
    "ko": "감도:"
  },
  {
    "key": "modal.cancel",
    "zh": "取消",
    "en": "Cancel",
    "es": "Cancelar",
    "de": "Stornieren",
    "ja": "キャンセル",
    "ru": "Отменено",
    "fr": "Annulez.",
    "pt": "Cancelar",
    "uk": "Скасувати",
    "nl": "annuleren",
    "ko": "취소"
  },
  {
    "key": "modal.confirm",
    "zh": "确认",
    "en": "Confirm",
    "es": "Confirmar",
    "de": "bestätigen",
    "ja": "確認",
    "ru": "Подтвердить",
    "fr": "Confirmez.",
    "pt": "Confirmar",
    "uk": "Підтвердити",
    "nl": "bevestigen",
    "ko": "확인"
  },
  {
    "key": "footer.brightness",
    "zh": "亮度",
    "en": "Brightness",
    "es": "Brillo",
    "de": "Helligkeit",
    "ja": "輝度",
    "ru": "Яркость",
    "fr": "luminosité",
    "pt": "Brilho",
    "uk": "Яскравість",
    "nl": "helderheid",
    "ko": "밝기"
  },
  {
    "key": "footer.more",
    "zh": "更多",
    "en": "More",
    "es": "Más",
    "de": "mehr",
    "ja": "もっと",
    "ru": "Больше",
    "fr": "plus",
    "pt": "Mais",
    "uk": "Більше",
    "nl": "meer",
    "ko": "추가"
  },
  {
    "key": "footer.countDown",
    "zh": "倒计时",
    "en": "Count Down",
    "es": "Olvídalo",
    "de": "Zählen nach unten",
    "ja": "カウントダウン",
    "ru": "Отсчет времени",
    "fr": "Compte à rebours",
    "pt": "Contagem decrescente",
    "uk": "Відлік часу",
    "nl": "aftellen",
    "ko": "카운트다운"
  },
  {
    "key": "footer.timing",
    "zh": "定时",
    "en": "Timing",
    "es": "Oportunidad",
    "de": "Timing",
    "ja": "タイミング",
    "ru": "Время",
    "fr": "calendrier",
    "pt": "Tempo",
    "uk": "Терміни",
    "nl": "timing",
    "ko": "스케줄"
  },
  {
    "key": "color.effect5",
    "zh": "浪漫",
    "en": "Romantic",
    "es": "Romance",
    "de": "romantisch",
    "ja": "ロマンチックな",
    "ru": "Романтический",
    "fr": "romantique",
    "pt": "Romântico",
    "uk": "Романтичний",
    "nl": "romantisch",
    "ko": "낭만적"
  },
  {
    "key": "diy.speed",
    "zh": "速度",
    "en": "Speed",
    "es": "Velocidad",
    "de": "Geschwindigkeit",
    "ja": "速度",
    "ru": "Скорость",
    "fr": "vitesse",
    "pt": "Velocidade",
    "uk": "Швидкість",
    "nl": "snelheid",
    "ko": "속도"
  },
  {
    "key": "diy.mode",
    "zh": "模式",
    "en": "Mode",
    "es": "Patrón",
    "de": "Muster",
    "ja": "モード",
    "ru": "Режим",
    "fr": "Mode",
    "pt": "Modo",
    "uk": "Режим",
    "nl": "patroon",
    "ko": "모드"
  },
  {
    "key": "diy.save",
    "zh": "保存",
    "en": "Save",
    "es": "Guardar",
    "de": "Erhaltung",
    "ja": "救う",
    "ru": "Сохранить",
    "fr": "Save",
    "pt": "Gravar",
    "uk": "Рятувати",
    "nl": "conservering",
    "ko": "구원"
  },
  {
    "key": "defaultName",
    "zh": "点阵屏",
    "en": "Lattice",
    "es": "Lattice",
    "de": "Gitter",
    "ja": "階魔法灯籠",
    "ru": "Заготовленный фонарь",
    "fr": "Ruban coulissant",
    "pt": "Lanterna mágica de assoalho",
    "uk": "Підлоговий чарівний ліхтар",
    "nl": "Gitterscherm",
    "ko": "격자나무 틀"
  },
  {
    "key": "timingLights",
    "zh": "定时开灯",
    "en": "Timing lights",
    "es": "Encienda la luz a tiempo",
    "de": "Machen Sie das Licht regelmäßig an",
    "ja": "タイミングライト",
    "ru": "Время включения света",
    "fr": "Allumage temporel des lumières",
    "pt": "Luzes de tempo",
    "uk": "Вогні ГРМ",
    "nl": "Doe regelmatig het licht aan",
    "ko": "정시등"
  },
  {
    "key": "turnOffLights",
    "zh": "定时关灯",
    "en": "Time to turn off the lights",
    "es": "Apagar la luz a tiempo",
    "de": "Schalten Sie die Lichter regelmäßig aus",
    "ja": "明かりを消す時間だ",
    "ru": "Выключите свет",
    "fr": "Éteignez les lumières à temps",
    "pt": "Hora de apagar as luzes.",
    "uk": "Час вимикати світло",
    "nl": "Doe regelmatig het licht uit",
    "ko": "불 끌 시간이에요."
  },
  {
    "key": "time",
    "zh": "时间",
    "en": "Time",
    "es": "Tiempo",
    "de": "Zeit",
    "ja": "時間",
    "ru": "Время",
    "fr": "Le temps",
    "pt": "Tempo",
    "uk": "Час",
    "nl": "tijd",
    "ko": "시간"
  },
  {
    "key": "repeatTime",
    "zh": "重复",
    "en": "Repeat",
    "es": "Repetir",
    "de": "Wiederholen",
    "ja": "繰り返す",
    "ru": "Повторить",
    "fr": "Répéter",
    "pt": "Repetir",
    "uk": "Повторити",
    "nl": "herhalen",
    "ko": "반복"
  },
  {
    "key": "microphone",
    "zh": "手机麦",
    "en": "Microphone",
    "es": "Micrófono",
    "de": "Mikrofon für Mobiltelefone",
    "ja": "マイクロフォン",
    "ru": "микрофон",
    "fr": "Microphone",
    "pt": "Microfone",
    "uk": "Мікрофон",
    "nl": "Mobiele telefoon microfoon",
    "ko": "마이크"
  },
  {
    "key": "microdevice",
    "zh": "外麦",
    "en": "Microdevice",
    "es": "MicróInstalación",
    "de": "Weizen außerhalb",
    "ja": "Microdevice",
    "ru": "Внешняя пшеница",
    "fr": "Blé extérieur",
    "pt": "Microdispositivo",
    "uk": "Мікропристрій",
    "nl": "Externe tarwe",
    "ko": "소형 장치"
  },
  {
    "key": "sensitivity",
    "zh": "灵敏度",
    "en": "Sensitivity",
    "es": "Sensibilidad",
    "de": "Empfindlichkeit",
    "ja": "感度",
    "ru": "Чувствительность",
    "fr": "Sensibilité",
    "pt": "Sensibilidade",
    "uk": "Чутливість",
    "nl": "gevoeligheid",
    "ko": "자상하다"
  },
  {
    "key": "microphonePermissions",
    "zh": "请打开麦克风权限",
    "en": "Please turn on microphone permissions",
    "es": "Por favor, abra los permisos del micrófono",
    "de": "Bitte schalten Sie Mikrofon-Berechtigungen ein",
    "ja": "マイクの権限をオンにしてください",
    "ru": "Включите разрешения микрофона",
    "fr": "Veuillez activer les permissions du microphone",
    "pt": "Por favor, ligue as permissões do microfone.",
    "uk": "Будь ласка, увімкніть дозволи мікрофона",
    "nl": "Schakel microfoonmachtiging in",
    "ko": "마이크 사용 권한을 켜십시오."
  },
  {
    "key": "tab.music",
    "zh": "音乐",
    "en": "Music",
    "es": "Música",
    "de": "Musik",
    "ja": "音楽",
    "ru": "Музыка",
    "fr": "musique",
    "pt": "Música",
    "uk": "Музика",
    "nl": "muziek",
    "ko": "음악"
  },
  {
    "key": "txt",
    "zh": "文本",
    "en": "Text",
    "es": "Texto",
    "de": "Text",
    "ja": "テキスト",
    "ru": "Текст",
    "fr": "Texte",
    "pt": "texto",
    "uk": "Текст",
    "nl": "tekst",
    "ko": "텍스트"
  },
  {
    "key": "gallery",
    "zh": "图库",
    "en": "gallery",
    "es": "Galería",
    "de": "Galerie",
    "ja": "ギャラリー",
    "ru": "Туку",
    "fr": "Galerie",
    "pt": "galeria",
    "uk": "галерея",
    "nl": "gallery",
    "ko": "진열실"
  },
  {
    "key": "diy",
    "zh": "DIY",
    "en": "DIY",
    "es": "Hazlo tú mismo.",
    "de": "DIY",
    "ja": "DIY",
    "ru": "Ди",
    "fr": "DIY",
    "pt": "DIY",
    "uk": "Своїми руками",
    "nl": "DIY",
    "ko": "DIY"
  },
  {
    "key": "rhythm",
    "zh": "律动",
    "en": "Rhythm",
    "es": "Ritmo",
    "de": "Rhythmus",
    "ja": "リズム",
    "ru": "Правом",
    "fr": "Mouvement de la loi",
    "pt": "Ritmo",
    "uk": "Ритм",
    "nl": "Ritme",
    "ko": "리듬"
  },
  {
    "key": "fixed",
    "zh": "固定",
    "en": "Fixed",
    "es": "Reparado",
    "de": "Fest",
    "ja": "こてい",
    "ru": "Фиксирование",
    "fr": "Fixe",
    "pt": "fixo",
    "uk": "Фіксована",
    "nl": "vast",
    "ko": "고정적"
  },
  {
    "key": "shiftLeft",
    "zh": "左移",
    "en": "Shift Left",
    "es": "Desplazamiento a la izquierda",
    "de": "Nach links verschieben",
    "ja": "左へ移動",
    "ru": "Переместить налево",
    "fr": "Déplacement à gauche",
    "pt": "Mover para a esquerda",
    "uk": "Зсув вліво",
    "nl": "Naar links bewegen",
    "ko": "왼쪽으로 이동"
  },
  {
    "key": "shiftRight",
    "zh": "右移",
    "en": "Shift right",
    "es": "Mover a la derecha",
    "de": "Nach rechts bewegen",
    "ja": "右へ移動",
    "ru": "Направо.",
    "fr": "Déplacement à droite",
    "pt": "Mover para a direita",
    "uk": "Зсув вправо",
    "nl": "Naar rechts gaan",
    "ko": "오른쪽으로 이동"
  },
  {
    "key": "moveDown",
    "zh": "下移",
    "en": "Move down",
    "es": "Mover hacia abajo",
    "de": "Sich abwärts bewegen",
    "ja": "下へ移動",
    "ru": "Переместить вниз",
    "fr": "Descendre",
    "pt": "Mover para Baixo",
    "uk": "Перемістити вниз",
    "nl": "Naar beneden schuiven",
    "ko": "아래로 이동"
  },
  {
    "key": "moveUp",
    "zh": "上移",
    "en": "Move up",
    "es": "Ascender",
    "de": "Bewegen Sie sich nach oben",
    "ja": "上へ移動",
    "ru": "Переместить вверх",
    "fr": "Déplacement vers le Haut",
    "pt": "Mover para cima",
    "uk": "Перемістити вгору",
    "nl": "Naar boven gaan",
    "ko": "위로 이동"
  },
  {
    "key": "flicker",
    "zh": "闪烁",
    "en": "Flicker",
    "es": "Parpadeo",
    "de": "Flackern",
    "ja": "きらめき",
    "ru": "Мерцание",
    "fr": "Clignotant",
    "pt": "cintilar",
    "uk": "Мерехтіння",
    "nl": "twinkelen",
    "ko": "깜박임"
  },
  {
    "key": "breathe",
    "zh": "呼吸",
    "en": "Breathe",
    "es": "Respirar",
    "de": "Durchatmen",
    "ja": "呼吸する",
    "ru": "Дыши.",
    "fr": "La respiration",
    "pt": "respiração",
    "uk": "Дихати",
    "nl": "ademhaling",
    "ko": "호흡"
  },
  {
    "key": "dynamic",
    "zh": "动态",
    "en": "Dynamic",
    "es": "Dinámica",
    "de": "Dynamisch",
    "ja": "動的",
    "ru": "Динамически",
    "fr": "Dynamique",
    "pt": "Dinâmica",
    "uk": "Динамічний",
    "nl": "dynamisch",
    "ko": "동적"
  },
  {
    "key": "static",
    "zh": "静态",
    "en": "Static",
    "es": "Estático",
    "de": "Statisch",
    "ja": "静的",
    "ru": "Статический",
    "fr": "Statique",
    "pt": "Estático",
    "uk": "Статичні",
    "nl": "statische toestand",
    "ko": "정지적"
  },
  {
    "key": "moreThanTen",
    "zh": "最多10个",
    "en": "More than 10",
    "es": "mas de 10",
    "de": "mehr als 10",
    "ja": "最大10",
    "ru": "Максимум 10.",
    "fr": "Jusqu'à 10",
    "pt": "Até 10",
    "uk": "Більше 10",
    "nl": "Tot tien",
    "ko": "10 초과"
  },
  {
    "key": "moreThanFive",
    "zh": "最多5个",
    "en": "More than 5",
    "es": "mas de 5",
    "de": "mehr als 5",
    "ja": "最大5",
    "ru": "Максимум пять.",
    "fr": "Jusqu'à 5",
    "pt": "Até 5",
    "uk": "Більше 5",
    "nl": "Tot 5",
    "ko": "5 초과"
  },
  {
    "key": "moreThan21",
    "zh": "最多21个",
    "en": "More than 21",
    "es": "mas de 21",
    "de": "mehr als 21",
    "ja": "最大21",
    "ru": "Максимум 21.",
    "fr": "Jusqu'à 21",
    "pt": "Até 21",
    "uk": "Більше 21",
    "nl": "Tot 21",
    "ko": "21 이상"
  },
  {
    "key": "moreThanFifty",
    "zh": "最多50个",
    "en": "More than 50",
    "es": "mas de 50",
    "de": "mehr als 50",
    "ja": "最大50",
    "ru": "Максимум 50.",
    "fr": "Jusqu'à 50",
    "pt": "Até 50",
    "uk": "Більше 50",
    "nl": "Tot 50",
    "ko": "50 이상"
  },
  {
    "key": "dimming",
    "zh": "调光",
    "en": "Dimming",
    "es": "Regulación",
    "de": "Dimmen",
    "ja": "調光",
    "ru": "Настройте свет",
    "fr": "Dimming",
    "pt": "Diminuição",
    "uk": "затемнення",
    "nl": "dimmen",
    "ko": "조광",
    "th": "ปรับความสว่าง",
    "ar": "تعتيم"
  },
  {
    "key": "scene",
    "zh": "场景",
    "en": "Scene",
    "es": "Escena",
    "de": "Szene",
    "ja": "シーン",
    "ru": "Сцена",
    "fr": "Scénario",
    "pt": "cena",
    "uk": "Сцени",
    "nl": "scenario",
    "ko": "장면",
    "th": "ฉาก",
    "ar": "مشهد"
  },
  {
    "key": "brightness",
    "zh": "亮度",
    "en": "Brightness",
    "es": "Brillo",
    "de": "Helligkeit",
    "ja": "輝度",
    "ru": "Яркость",
    "fr": "Luminosité",
    "pt": "brilho",
    "uk": "Яскравість",
    "nl": "luminantie",
    "ko": "밝기",
    "th": "ความสว่าง",
    "ar": "السطوع"
  },
  {
    "key": "more",
    "zh": "更多",
    "en": "More",
    "es": "Más",
    "de": "Mehr",
    "ja": "もっと",
    "ru": "Больше",
    "fr": "Plus",
    "pt": "mais",
    "uk": "Більше",
    "nl": "meer",
    "ko": "추가",
    "th": "เพิ่มเติม",
    "ar": "المزيد"
  },
  {
    "key": "timing",
    "zh": "定时",
    "en": "Timer",
    "es": "Oportunidad",
    "de": "Zeitliche Koordinierung",
    "ja": "タイミング",
    "ru": "Время",
    "fr": "Timing",
    "pt": "cronometragem",
    "uk": "Терміни",
    "nl": "timing",
    "ko": "정시",
    "th": "ตัวจับเวลา",
    "ar": "مؤقت"
  },
  {
    "key": "countdown",
    "zh": "倒计时",
    "en": "Countdown",
    "es": "Cuenta atrás",
    "de": "Countdown",
    "ja": "カウントダウン",
    "ru": "Отсчет времени",
    "fr": "Compte à rebours",
    "pt": "contagem decrescente",
    "uk": "Відлік часу",
    "nl": "aftellen",
    "ko": "카운트다운",
    "th": "นับถอยหลัง",
    "ar": "عد تنازلي"
  },
  {
    "key": "singleGradient",
    "zh": "单色渐变",
    "en": "Gradient1",
    "es": "Gradiente1",
    "de": "Farbverlauf1",
    "ja": "Gradient1",
    "ru": "Монохромный градиент",
    "fr": "Gradient monochrome",
    "pt": "Gradiente monocromático",
    "uk": "Градієнт1",
    "nl": "Gradient1",
    "ko": "단색 그라데이션",
    "th": "ไล่ระดับสีเดียว",
    "ar": "تدرج1"
  },
  {
    "key": "ThreeColorGradient",
    "zh": "三色渐变",
    "en": "Gradient3",
    "es": "Gradiente3",
    "de": "Farbverlauf3",
    "ja": "Gradient3",
    "ru": "Трехцветный градиент",
    "fr": "Gradient tricolore",
    "pt": "Gradiente de três cores",
    "uk": "Градієнт3",
    "nl": "Gradient3",
    "ko": "3색 그라데이션",
    "th": "ไล่ระดับสีสามสี",
    "ar": "تدرج3"
  },
  {
    "key": "sevenColorGradient",
    "zh": "七色渐变",
    "en": "Gradient7",
    "es": "Gradiente7",
    "de": "Farbverlauf7",
    "ja": "Gradient7",
    "ru": "Градиент по семи цветам",
    "fr": "Gradient de sept couleurs",
    "pt": "Gradiente de sete cores",
    "uk": "Градієнт7",
    "nl": "Gradient7",
    "ko": "7색 그라데이션",
    "th": "ไล่ระดับสีเจ็ดสี",
    "ar": "تدرج7"
  },
  {
    "key": "singleJump",
    "zh": "单色跳变",
    "en": "Jump1",
    "es": "Salto1",
    "de": "Sprung1",
    "ja": "Jump1",
    "ru": "Монохромный переход",
    "fr": "Saut monochromatique",
    "pt": "Salto monocromático",
    "uk": "Стрибок1",
    "nl": "Jump1",
    "ko": "단색 변환",
    "th": "เปลี่ยนสีเดียว",
    "ar": "قفز1"
  },
  {
    "key": "ThreeColorJump",
    "zh": "三色跳变",
    "en": "Jump3",
    "es": "Salto3",
    "de": "Sprung3",
    "ja": "Jump3",
    "ru": "Три цвета прыгают",
    "fr": "Saut tricolore",
    "pt": "Salto tricromático",
    "uk": "Стрибок3",
    "nl": "Jump3",
    "ko": "삼색 변화",
    "th": "เปลี่ยนสีสามสี",
    "ar": "قفز3"
  },
  {
    "key": "sevenColorJump",
    "zh": "七色跳变",
    "en": "Jump7",
    "es": "Salto7",
    "de": "Sprung7",
    "ja": "Jump7",
    "ru": "Семь цветов прыгают",
    "fr": "Saut de sept couleurs",
    "pt": "Salto de sete cores",
    "uk": "Стрибок7",
    "nl": "Jump7",
    "ko": "칠색 변화",
    "th": "เปลี่ยนสีเจ็ดสี",
    "ar": "قفز7"
  },
  {
    "key": "singleBreathe",
    "zh": "单色呼吸",
    "en": "Breathe1",
    "es": "Respiración1",
    "de": "Atmen1",
    "ja": "Breathe1",
    "ru": "Монохромное дыхание",
    "fr": "Respiration monochromatique",
    "pt": "Respiração monocromática",
    "uk": "Дихайте1",
    "nl": "Breathe1",
    "ko": "단색 호흡",
    "th": "หายใจสีเดียว",
    "ar": "تنفس1"
  },
  {
    "key": "ThreeBreathe",
    "zh": "三色呼吸",
    "en": "Breathe3",
    "es": "Respiración3",
    "de": "Atmen3",
    "ja": "Breathe3",
    "ru": "Дыши тремя цветами",
    "fr": "Respiration tricolore",
    "pt": "Respiração tricromática",
    "uk": "Дихайте3",
    "nl": "Breathe3",
    "ko": "삼색호흡",
    "th": "หายใจสามสี",
    "ar": "تنفس3"
  },
  {
    "key": "sevenBreathe",
    "zh": "七色呼吸",
    "en": "Breathe7",
    "es": "Respiración7",
    "de": "Atmen7",
    "ja": "Breathe7",
    "ru": "Дыши по семи цветам",
    "fr": "Respiration en sept couleurs",
    "pt": "Respiração de sete cores",
    "uk": "Дихайте7",
    "nl": "Breathe7",
    "ko": "칠색 호흡",
    "th": "หายใจเจ็ดสี",
    "ar": "تنفس7"
  },
  {
    "key": "singleStrobe",
    "zh": "单色频闪",
    "en": "Strobe1",
    "es": "Estroboscopio1",
    "de": "Blitz1",
    "ja": "Strobe1",
    "ru": "Монохромная стробость",
    "fr": "Stroboscope monochrome",
    "pt": "Estroboscópico monocromático",
    "uk": "Строби1",
    "nl": "Strobe1",
    "ko": "단색 번개",
    "th": "แสบสีเดียว",
    "ar": "وميض1"
  },
  {
    "key": "ThreeStrobe",
    "zh": "三色频闪",
    "en": "Strobe3",
    "es": "Estroboscopio3",
    "de": "Blitz3",
    "ja": "Strobe3",
    "ru": "Трехмерная вспышка",
    "fr": "Stroboscope tricolore",
    "pt": "Estroboscópico tricromático",
    "uk": "Строби3",
    "nl": "Strobe3",
    "ko": "삼색 번개",
    "th": "แสบสามสี",
    "ar": "وميض3"
  },
  {
    "key": "sevenStrobe",
    "zh": "七色频闪",
    "en": "Strobe7",
    "es": "Estroboscopio7",
    "de": "Blitz7",
    "ja": "Strobe7",
    "ru": "С семицветным стробосиком",
    "fr": "Stroboscope à sept couleurs",
    "pt": "Estroboscópico de sete cores",
    "uk": "Строби7",
    "nl": "Strobe7",
    "ko": "칠색이 번쩍이다",
    "th": "แสบเจ็ดสี",
    "ar": "وميض7"
  },
  {
    "key": "speed",
    "zh": "速度",
    "en": "Speed",
    "es": "Velocidad",
    "de": "Geschwindigkeit",
    "ja": "速度",
    "ru": "Скорость",
    "fr": "Vitesse",
    "pt": "velocidade",
    "uk": "Швидкість",
    "nl": "snelheid",
    "ko": "속도",
    "th": "ความเร็ว",
    "ar": "السرعة"
  },
  {
    "key": "save",
    "zh": "保存",
    "en": "Save",
    "es": "Guardar",
    "de": "Speichern",
    "ja": "セーブ",
    "ru": "Сохранить",
    "fr": "Enregistrer",
    "pt": "preservação",
    "uk": "Рятувати",
    "nl": "behoud",
    "ko": "저장",
    "th": "บันทึก",
    "ar": "حفظ"
  },
  {
    "key": "editColor",
    "zh": "编辑颜色",
    "en": "Edit the color",
    "es": "Editar color",
    "de": "Bearbeiten Sie die Farbe",
    "ja": "編集色",
    "ru": "Изменить цвет",
    "fr": "Modifier la couleur",
    "pt": "Editar a cor",
    "uk": "Редагування кольору",
    "nl": "Kleur bewerken",
    "ko": "색상 편집",
    "th": "แก้ไขสี",
    "ar": "تعديل اللون"
  },
  {
    "key": "addTiming",
    "zh": "添加定时",
    "en": "Add the timer",
    "es": "Añadir tiempo",
    "de": "Füge das Timing hinzu",
    "ja": "タイミングを加え",
    "ru": "Добавить время",
    "fr": "Ajouter un timing",
    "pt": "Adicionar tempo",
    "uk": "Додавання хронометражу",
    "nl": "Extra tijd",
    "ko": "시간 추가",
    "th": "เพิ่มตัวจับเวลา",
    "ar": "إضافة مؤقت"
  },
  {
    "key": "timingTips",
    "zh": "定时可能存在30秒左右的误差",
    "en": "Timer may have an error of about 30 seconds",
    "es": "El tiempo puede tener un error de unos 30 segundos",
    "de": "Beim Timing kann ein Fehler von etwa 30 Sekunden auftreten",
    "ja": "タイミングには約30秒の誤差がある可能性があります",
    "ru": "Во время синхронизации может быть ошибка около 30 секунд",
    "fr": "Le timing peut avoir une erreur d'environ 30 secondes",
    "pt": "O tempo pode ter um erro de cerca de 30 segundos",
    "uk": "Хронометраж може мати похибку близько 30 секунд",
    "nl": "De timing kan een fout van ongeveer 30 seconden hebben",
    "ko": "정시에 30초 정도의 오차가 있을 수 있습니다.",
    "th": "ตัวจับเวลาอาจมีความผิดพลาดประมาณ 30 วินาที",
    "ar": "قد يكون هناك خطأ بنحو 30 ثانية"
  },
  {
    "key": "repeatTiming",
    "zh": "重复定时",
    "en": "Repeat timer",
    "es": "Tiempo de repetición",
    "de": "Timing wiederholen",
    "ja": "繰り返すタイミング",
    "ru": "Повторяйте время",
    "fr": "Répéter le timing",
    "pt": "Repetir o tempo",
    "uk": "Повторний хронометраж",
    "nl": "Tijd voor herhaling",
    "ko": "반복 시간",
    "th": "ตัวจับเวลาครั้งต่อครั้ง",
    "ar": "تكرار المؤقت"
  },
  {
    "key": "timing.exists",
    "zh": "已存在该定时",
    "en": "The timer already exists",
    "es": "Este tiempo ya existe",
    "de": "Das Timing ist bereits vorhanden",
    "ja": "タイミングは既にあった",
    "ru": "Время уже существует",
    "fr": "Le timing existe déjà",
    "pt": "O momento já existe.",
    "uk": "Терміни вже існують",
    "nl": "De tijd is er al",
    "ko": "이 시간이 이미 존재합니다",
    "th": "มีตัวจับเวลานี้อยู่แล้ว",
    "ar": "المؤقت موجود بالفعل"
  },
  {
    "key": "once",
    "zh": "仅限一次",
    "en": "Once",
    "es": "Sólo una vez",
    "de": "Wenn",
    "ja": "一度",
    "ru": "Только один раз",
    "fr": "Une seule fois",
    "pt": "Só uma vez",
    "uk": "Колись",
    "nl": "Een keer",
    "ko": "한 번만",
    "th": "ครั้งเดียว",
    "ar": "مرة واحدة"
  },
  {
    "key": "add",
    "zh": "添加",
    "en": "Add",
    "es": "Añadir",
    "de": "Hinzufügen",
    "ja": "追加",
    "ru": "Добавить",
    "fr": "Ajouter",
    "pt": "adicionar a",
    "uk": "Додати",
    "nl": "toevoeging",
    "ko": "추가",
    "th": "เพิ่ม",
    "ar": "إضافة"
  },
  {
    "key": "open",
    "zh": "开",
    "en": "Open",
    "es": "Abrir",
    "de": "Offen",
    "ja": "オープン",
    "ru": "Включи",
    "fr": "Vas - y.",
    "pt": "abrir",
    "uk": "Відкривати",
    "nl": "openheid",
    "ko": "켜기",
    "th": "เปิด",
    "ar": "فتح"
  },
  {
    "key": "close",
    "zh": "关",
    "en": "Close",
    "es": "Cerrar",
    "de": "Nah dran",
    "ja": "近い",
    "ru": "Закрыть",
    "fr": "Coupez.",
    "pt": "fechado",
    "uk": "Закрити",
    "nl": "gesloten",
    "ko": "끄기",
    "th": "ปิด",
    "ar": "إغلاق"
  },
  {
    "key": "closure",
    "zh": "关闭",
    "en": "closure",
    "es": "cierre",
    "de": "Schließung",
    "ja": "閉鎖",
    "ru": "закрыццё",
    "fr": "Fermer",
    "pt": "fechar",
    "uk": "Закриття",
    "nl": "gesloten",
    "ko": "닫기",
    "th": "ปิด",
    "ar": "إغلاق"
  },
  {
    "key": "switch",
    "zh": "开关",
    "en": "Switch",
    "es": "Interruptor",
    "de": "Schalter",
    "ja": "スイッチ",
    "ru": "Выключатель",
    "fr": "Switch",
    "pt": "interruptor",
    "uk": "Комутатор",
    "nl": "schakelaars",
    "ko": "스위치",
    "th": "สวิตช์",
    "ar": "مفتاح"
  },
  {
    "key": "storage",
    "zh": "储存",
    "en": "Storage",
    "es": "Almacenamiento",
    "de": "Lagerung",
    "ja": "記憶",
    "ru": "Хранение",
    "fr": "Stockage",
    "pt": "Armazenamento",
    "uk": "Зберігання",
    "nl": "opslag",
    "ko": "저장",
    "th": "จัดเก็บ",
    "ar": "تخزين"
  },
  {
    "key": "cancel",
    "zh": "取消",
    "en": "Cancel",
    "es": "Cancelar",
    "de": "Abbrechen",
    "ja": "キャンセル",
    "ru": "Отменено",
    "fr": "Annulation",
    "pt": "cancelar",
    "uk": "Скасувати",
    "nl": "vervallen",
    "ko": "취소",
    "th": "ยกเลิก",
    "ar": "إلغاء"
  },
  {
    "key": "hour",
    "zh": "时",
    "en": "H",
    "es": "H",
    "de": "H",
    "ja": "H",
    "ru": "Когда",
    "fr": "Heure",
    "pt": "Hora",
    "uk": "H",
    "nl": "H",
    "ko": "시",
    "th": "ชั่วโมง",
    "ar": "س"
  },
  {
    "key": "minutes",
    "zh": "分",
    "en": "M",
    "es": "M",
    "de": "M",
    "ja": "M",
    "ru": "Точка",
    "fr": "Points",
    "pt": "ramo",
    "uk": "M",
    "nl": "M.",
    "ko": "분할",
    "th": "นาที",
    "ar": "د"
  },
  {
    "key": "repeat",
    "zh": "重复",
    "en": "Repeat",
    "es": "Repetir",
    "de": "Wiederholen",
    "ja": "繰り返す",
    "ru": "Повторить",
    "fr": "Je répète.",
    "pt": "Repetir",
    "uk": "Повторити",
    "nl": "herhaling",
    "ko": "반복",
    "th": "ทำซ้ำ",
    "ar": "تكرار"
  },
  {
    "key": "everyDay",
    "zh": "每天",
    "en": "Every day",
    "es": "Todos los días",
    "de": "Jeden Tag",
    "ja": "毎日",
    "ru": "Каждый день",
    "fr": "Tous les jours",
    "pt": "Todos os dias",
    "uk": "Щодня",
    "nl": "Elke dag",
    "ko": "매일",
    "th": "ทุกวัน",
    "ar": "كل يوم"
  },
  {
    "key": "modifyTiming",
    "zh": "修改定时",
    "en": "Modify the timer",
    "es": "Modificar el tiempo",
    "de": "Ändern Sie das Timing",
    "ja": "タイミングを修正する",
    "ru": "Изменить время",
    "fr": "Modifier le timing",
    "pt": "Modificar o tempo",
    "uk": "Змінення хронометражу",
    "nl": "Tijd voor herziening",
    "ko": "수정 시간",
    "th": "แก้ไขตัวจับเวลา",
    "ar": "تعديل المؤقت"
  },
  {
    "key": "delete",
    "zh": "删除",
    "en": "Delete",
    "es": "Borrar",
    "de": "Löschen",
    "ja": "削除",
    "ru": "Удалить",
    "fr": "Supprimer",
    "pt": "apagar",
    "uk": "Видалити",
    "nl": "geschrapt",
    "ko": "삭제",
    "th": "ลบ",
    "ar": "حذف"
  },
  {
    "key": "determine",
    "zh": "确定",
    "en": "Confirm",
    "es": "Confirmar",
    "de": "Bestätigen",
    "ja": "確認する",
    "ru": "подтверждать",
    "fr": "Confirmer",
    "pt": "Confirme",
    "uk": "підтвердити",
    "nl": "bevestigen",
    "ko": "확인하다",
    "th": "ยืนยัน",
    "ar": "تأكيد"
  },
  {
    "key": "deviceDetails",
    "zh": "设备详情",
    "en": "Device details",
    "es": "Detalles del equipo",
    "de": "Gerätedetails",
    "ja": "装置詳細",
    "ru": "Детали оборудования",
    "fr": "Détails du matériel",
    "pt": "Detalhes do dispositivo",
    "uk": "Подробиці про пристрій",
    "nl": "Details van de apparatuur",
    "ko": "장치 상세 정보",
    "th": "รายละเอียดอุปกรณ์",
    "ar": "تفاصيل الجهاز"
  },
  {
    "key": "chooseTopic",
    "zh": "主题选择",
    "en": "Choose a theme",
    "es": "Selección de temas",
    "de": "Wähle ein Thema",
    "ja": "テーマを選ぶ",
    "ru": "Выбор темы",
    "fr": "Choix du thème",
    "pt": "Selecção de tópicos",
    "uk": "Виберіть тему",
    "nl": "Kies een onderwerp",
    "ko": "주제 선택",
    "th": "เลือกธีม",
    "ar": "اختر سمة"
  },
  {
    "key": "deviceName",
    "zh": "设备名称",
    "en": "Device name",
    "es": "Nombre del dispositivo",
    "de": "Gerätename",
    "ja": "デバイス名",
    "ru": "Имя оборудования",
    "fr": "Nom du matériel",
    "pt": "Nome do equipamento",
    "uk": "Назва пристрою",
    "nl": "Naam van het apparaat",
    "ko": "장치 이름",
    "th": "ชื่ออุปกรณ์",
    "ar": "اسم الجهاز"
  },
  {
    "key": "deviceID",
    "zh": "设备ID",
    "en": "Device ID",
    "es": "ID del dispositivo",
    "de": "Geräte ID",
    "ja": "機器ID",
    "ru": "Идентификатор оборудования",
    "fr": "ID du périphérique",
    "pt": "ID do dispositivo",
    "uk": "Ідентифікатор пристрою",
    "nl": "ID van het apparaat",
    "ko": "장치 ID",
    "th": "ID อุปกรณ์",
    "ar": "معرّف الجهاز"
  },
  {
    "key": "firmwareV",
    "zh": "固件版本",
    "en": "Firmware Ver",
    "es": "Versión del firmware",
    "de": "Firmware Ver",
    "ja": "ファームウェアVer",
    "ru": "Версия микропрограммы",
    "fr": "Version firmware",
    "pt": "Versão do firmware",
    "uk": "Прошивка Ver",
    "nl": "Firmware versie",
    "ko": "펌웨어 버전",
    "th": "เวอร์ชันเฟิร์มแวร์",
    "ar": "إصدار البرنامج الثابت"
  },
  {
    "key": "share",
    "zh": "共享设备",
    "en": "Share equipment",
    "es": "Dispositivo compartido",
    "de": "Ausrüstung teilen",
    "ja": "共有装置",
    "ru": "Общее оборудование",
    "fr": "Dispositifs partagés",
    "pt": "Dispositivos partilhados",
    "uk": "Спільне обладнання",
    "nl": "Gedeelde apparatuur",
    "ko": "공유 장치",
    "th": "แชร์อุปกรณ์",
    "ar": "مشاركة الجهاز"
  },
  {
    "key": "feedback",
    "zh": "常见问题与反馈",
    "en": "FAQ",
    "es": "Preguntas más frecuentes",
    "de": "FAQ",
    "ja": "FAQ",
    "ru": "Часто задаваемые вопросы и отзывы",
    "fr": "FAQ & feedback",
    "pt": "Problemas comuns e feedback",
    "uk": "Питання-відповіді",
    "nl": "Veelgestelde vragen",
    "ko": "FAQ 및 피드백",
    "th": "คำถามที่พบบ่อยและ피드บแคค",
    "ar": "الأسئلة الشائعة"
  },
  {
    "key": "remove",
    "zh": "移除设备",
    "en": "Remove equipment",
    "es": "Eliminar dispositivo",
    "de": "Geräte entfernen",
    "ja": "除去装置",
    "ru": "Удалить устройство",
    "fr": "Supprimer l'appareil",
    "pt": "Remover o dispositivo",
    "uk": "Видалення обладнання",
    "nl": "Verwijderen van apparatuur",
    "ko": "장치 제거",
    "th": "นำอุปกรณ์ออก",
    "ar": "إزالة الجهاز"
  },
  {
    "key": "modify",
    "zh": "重命名",
    "en": "Modify the title",
    "es": "Renombrar",
    "de": "Ändern Sie den Titel",
    "ja": "タイトルを修正する",
    "ru": "Переименование",
    "fr": "Renommer",
    "pt": "renomear",
    "uk": "Змінення заголовка",
    "nl": "Wijziging van de titel",
    "ko": "이름 바꾸기",
    "th": "เปลี่ยนชื่อ",
    "ar": "إعادة تسمية"
  },
  {
    "key": "deleteOrNot",
    "zh": "是否删除",
    "en": "Delete or not",
    "es": "Borrar",
    "de": "Löschen oder nicht",
    "ja": "削除まい",
    "ru": "Удалить",
    "fr": "Supprimer ou non",
    "pt": "Apagar",
    "uk": "Видаляти чи ні",
    "nl": "Al dan niet geschrapt",
    "ko": "삭제 여부",
    "th": "ลบหรือไม่",
    "ar": "حذف أم لا"
  },
  {
    "key": "theme",
    "zh": "主题",
    "en": "Theme",
    "es": "Tema",
    "de": "Thema",
    "ja": "テーマ",
    "ru": "Тема",
    "fr": "Objet",
    "pt": "tema",
    "uk": "Тема",
    "nl": "onderwerp",
    "ko": "주제",
    "th": "ธีม",
    "ar": "السمة"
  },
  {
    "key": "offline.title",
    "zh": "设备连接失败",
    "en": "Device connection failed",
    "es": "Fallo de conexión del dispositivo",
    "de": "Geräteverbindung fehlgeschlagen",
    "ja": "装置接続ができなかった。",
    "ru": "Не удалось подключиться к устройству",
    "fr": "Défaillance de la connexion du périphérique",
    "pt": "Falha na ligação do dispositivo",
    "uk": "Помилка підключення пристрою",
    "nl": "Mislukte verbinding van het apparaat",
    "ko": "장치 연결 실패",
    "th": "การเชื่อมต่อกับอุปกรณ์ล้มเหลว",
    "ar": "فشل اتصال الجهاز"
  },
  {
    "key": "offline.checkSequentially",
    "zh": "请依次检查",
    "en": "Please check sequentially",
    "es": "Por favor revise secuencialmente",
    "de": "Bitte nacheinander prüfen",
    "ja": "順次調べてください",
    "ru": "Проверьте по очереди",
    "fr": "Vérifiez à tour de rôle.",
    "pt": "Por favor, verifique por sua vez.",
    "uk": "Будь ласка, перевіряйте послідовно",
    "nl": "Gelieve te controleren in volgorde",
    "ko": "차례차례 검사하시오",
    "th": "โปรดตรวจสอบตามลำดับ",
    "ar": "يرجى التحقق بالتسلسل"
  },
  {
    "key": "offline.checkOne",
    "zh": "请检查您的设备是否有电",
    "en": "Please check if your device has power",
    "es": "Comprueba si tu dispositivo tiene energía",
    "de": "Bitte überprüfen Sie, ob Ihr Gerät mit Strom versorgt wird",
    "ja": "お使いのデバイスに電源が入っているか確認してください",
    "ru": "Проверьте устройство на наличие электричества",
    "fr": "Veuillez vérifier si votre appareil est alimenté",
    "pt": "Verifique se o seu dispositivo tem energia",
    "uk": "Будь ласка, перевірте, чи є живлення вашого пристрою",
    "nl": "Controleer of uw apparaat stroom heeft",
    "ko": "장치의 전원을 확인하십시오.",
    "th": "โปรดตรวจสอบว่าอุปกรณ์ของคุณมีไฟฟ้าหรือไม่",
    "ar": "تحقق من وجود طاقة بالجهاز"
  },
  {
    "key": "offline.checkTwo",
    "zh": "您的设备连接的路由器是否正常工作",
    "en": "Is the router connected to your device working",
    "es": "¿El enrutador conectado a su dispositivo funciona correctamente?",
    "de": "Funktioniert der Router, der mit Ihrem Gerät verbunden ist?",
    "ja": "あなたのデバイスに接続されているルーターは機能していますか",
    "ru": "Правильно ли работает маршрутизатор, к которому подключено ваше устройство",
    "fr": "Le routeur auquel votre appareil est connecté fonctionne - t - il correctement?",
    "pt": "O roteador está conectado ao seu dispositivo funcionando corretamente",
    "uk": "Чи працює маршрутизатор, підключений до вашого пристрою",
    "nl": "Of de router is aangesloten op uw apparaat werkt goed",
    "ko": "장치에 연결된 라우터가 작동하는지 여부",
    "th": "เราเตอร์ที่เชื่อมต่อกับอุปกรณ์ของคุณทำงานปกติหรือไม่",
    "ar": "هل الموجه المتصل بالجهاز يعمل؟"
  },
  {
    "key": "offline.checkThree",
    "zh": "检查是否修改了路由器的名称或密码，可以尝试重新连接",
    "en": "Check whether the name or password of the router has been modified, you can try to reconnect",
    "es": "Compruebe si se ha modificado el nombre o la contraseña del enrutador, puede intentar volver a conectarse",
    "de": "Überprüfen Sie, ob der Name oder das Passwort des Routers geändert wurde, Sie können versuchen, sich erneut zu verbinden",
    "ja": "ルータの名前またはパスワードが変更されているかどうかを確認し、再接続を試みることができます",
    "ru": "Проверьте, было ли изменено имя или пароль маршрутизатора, и вы можете попытаться подключиться снова",
    "fr": "Vérifiez si le nom ou le mot de passe du routeur a été modifié et essayez de vous reconnecter",
    "pt": "Verifique se o nome ou senha do roteador foi modificado e você pode tentar reconectar",
    "uk": "Перевірте, чи було змінено ім'я або пароль роутера, можна спробувати підключитися заново",
    "nl": "Controleer of de naam of het wachtwoord van de router is gewijzigd en probeer opnieuw te verbinden",
    "ko": "라우터의 이름이나 암호가 수정되었는지 확인하여 다시 연결할 수 있습니다.",
    "th": "ตรวจสอบว่าชื่อหรือรหัสผ่านของเราเตอร์ถูกแก้ไขหรือไม่ คุณสามารถลองเชื่อมต่อใหม่ได้",
    "ar": "تحقق من اسم الموجه أو كلمة مروره ثم أعد الاتصال"
  },
  {
    "key": "offline.checkfour",
    "zh": "您的设备是否离路由器过远，信号较差或有遮挡物",
    "en": "Is your device too far from the router, poor signal or obstructing",
    "es": "¿Está su dispositivo demasiado lejos del enrutador, tiene poca señal u obstruye",
    "de": "Ist Ihr Gerät zu weit vom Router entfernt, schlechtes Signal oder behindert",
    "ja": "デバイスがルーターから遠すぎたり、信号が悪くなったり、邪魔になったりしていませんか",
    "ru": "Далеко ли ваше устройство от маршрутизатора, сигнал плохой или затененный",
    "fr": "Votre appareil est - il trop loin de votre routeur, a - t - il un mauvais signal ou est - il bloqué?",
    "pt": "Seu dispositivo está muito longe do roteador, com sinal ruim ou obstruções",
    "uk": "Ваш пристрій занадто далеко від маршрутизатора, поганий сигнал або перешкоджання",
    "nl": "Is uw apparaat te ver van de router, een slecht signaal of een obstakel",
    "ko": "장치가 라우터에서 너무 멀리 떨어져 있는지, 신호가 낮거나 가림막이 있는지 여부",
    "th": "อุปกรณ์ของคุณอยู่ห่างจากเราเตอร์มากเกินไปหรือไม่ สัญญาณอ่อนหรือมีของขวาง",
    "ar": "هل الجهاز بعيد عن الموجه أو الإشارة ضعيفة؟"
  },
  {
    "key": "offline.checkFive",
    "zh": "将手机尽量靠近设备",
    "en": "Keep the phone as close to the device as possible",
    "es": "Mueva el teléfono lo más cerca posible del dispositivo",
    "de": "Halten Sie das Telefon so nah wie möglich am Gerät",
    "ja": "携帯電話をできるだけデバイスに近づけてください",
    "ru": "Держите телефон как можно ближе к устройству",
    "fr": "Gardez votre téléphone aussi près que possible de l'appareil",
    "pt": "Mantenha o telefone o mais próximo possível do dispositivo",
    "uk": "Тримайте телефон якомога ближче до пристрою",
    "nl": "Houd uw telefoon zo dicht mogelijk bij het apparaat",
    "ko": "휴대폰을 최대한 기기에 가까이",
    "th": "นำโทรศัพท์มือถือใกล้อุปกรณ์เท่าที่สุด",
    "ar": "قرّب الهاتف من الجهاز قدر الإمكان"
  },
  {
    "key": "offline.checkSix",
    "zh": "如果设备被其他手机连接过，请先断开之前的连接",
    "en": "If the device has been connected by other mobile phones, please disconnect the previous connection first",
    "es": "Si el dispositivo ha sido conectado por otros teléfonos móviles, primero desconecte la conexión anterior",
    "de": "Wenn das Gerät von anderen Mobiltelefonen verbunden wurde, trennen Sie bitte zuerst die vorherige Verbindung",
    "ja": "他の携帯電話で接続されている場合は、先に接続を解除してください",
    "ru": "Если устройство подключено к другому мобильному телефону, сначала отключите предыдущее подключение",
    "fr": "Si l'appareil est connecté à un autre téléphone, débranchez d'abord la connexion précédente.",
    "pt": "Se o dispositivo foi conectado por outros telefones celulares, desconecte-o primeiro",
    "uk": "Якщо пристрій було підключено іншими мобільними телефонами, спочатку відключіть попереднє з'єднання",
    "nl": "Als het apparaat is verbonden met een andere telefoon, maak dan eerst de vorige verbinding los",
    "ko": "기기가 다른 휴대폰에 연결되어 있으면 먼저 이전 연결을 끊으십시오.",
    "th": "หากอุปกรณ์ถูกเชื่อมต่อด้วยโทรศัพท์มือถืออื่น โปรดแยกการเชื่อมต่อที่ผ่านมาเป็นอันดับแรก",
    "ar": "افصل أي اتصال سابق بالجهاز أولاً"
  },
  {
    "key": "offline.FAQ",
    "zh": "常见问题与反馈",
    "en": "FAQ",
    "es": "Preguntas más frecuentes",
    "de": "FAQ",
    "ja": "FAQ",
    "ru": "Часто задаваемые вопросы и отзывы",
    "fr": "FAQ & feedback",
    "pt": "Problemas comuns e feedback",
    "uk": "Питання-відповіді",
    "nl": "Veelgestelde vragen",
    "ko": "FAQ 및 피드백",
    "th": "คำถามที่พบบ่อยและ피드บแคค",
    "ar": "الأسئلة الشائعة"
  },
  {
    "key": "remainingTime",
    "zh": "剩余时间",
    "en": "Remaining time",
    "es": "tiempo restante",
    "de": "Verbleibende Zeit",
    "ja": "残り時間",
    "ru": "Остальное время",
    "fr": "Temps restant",
    "pt": "Tempo restante",
    "uk": "Час, що залишився",
    "nl": "Overige tijd",
    "ko": "남은 시간",
    "th": "เวลาที่เหลือ",
    "ar": "الوقت المتبقي"
  },
  {
    "key": "copySuccessfully",
    "zh": "复制成功",
    "en": "Copy successfully",
    "es": "Copiar con éxito",
    "de": "Erfolgreich kopieren",
    "ja": "コピー成功",
    "ru": "Репликация прошла успешно",
    "fr": "Copie réussie",
    "pt": "A cópia foi bem sucedida",
    "uk": "Успішно скопіювати",
    "nl": "Succesvol kopieren",
    "ko": "복제 성공",
    "th": "คัดลอกสำเร็จ",
    "ar": "تم النسخ بنجاح"
  },
  {
    "key": "EwFiveMinutes",
    "zh": "(五分钟之内有效)",
    "en": "Effective within five minutes",
    "es": "Efectivo en cinco minutos",
    "de": "Wirksam innerhalb von fünf Minuten",
    "ja": "5分以内に",
    "ru": "Действует в течение пяти минут )",
    "fr": "(valable dans cinq minutes)",
    "pt": "(válido dentro de cinco minutos)",
    "uk": "Ефективний протягом п'яти хвилин",
    "nl": "Inwerkingtreding binnen 5 minuten",
    "ko": "(5분 이내 유효)",
    "th": "(มีอายุการใช้งานภายใน 5 นาที)",
    "ar": "صالح خلال خمس دقائق"
  },
  {
    "key": "seconds",
    "zh": "秒",
    "en": "S",
    "es": "Segundo",
    "de": "S",
    "ja": "S",
    "ru": "С",
    "fr": "Secondes",
    "pt": "segundo",
    "uk": "S",
    "nl": "jaar",
    "ko": "초",
    "th": "วินาที",
    "ar": "ث"
  },
  {
    "key": "timersReachedMax",
    "zh": "定时个数已达上限,请修改或删除已有定时",
    "en": "The maximum number of timers has been reached. Please modify or delete the existing timers",
    "es": "El número de tiempos ha alcanzado el límite superior, por favor modifique o elimine los tiempos existentes",
    "de": "Die maximale Anzahl von Timern wurde erreicht. Bitte ändern oder löschen Sie die vorhandenen Timer",
    "ja": "タイマーの最大数に達しました。既存のタイマーを修正または削除してください",
    "ru": "Количество часов достигло верхнего предела, пожалуйста, измените или удалите, что уже есть время",
    "fr": "Le nombre de timings a atteint la limite supérieure. Veuillez modifier ou supprimer les timings existants.",
    "pt": "O número de tempo fixo atingiu o limite superior, modifique ou exclua o tempo fixo existente",
    "uk": "Досягнуто максимальної кількості таймерів. Будь ласка, змініть або видаліть існуючі таймери",
    "nl": "Het maximum aantal timers is bereikt. Een bestaande timer wijzigen of verwijderen",
    "ko": "타이밍 개수가 이미 상한에 도달했습니다. 타이밍을 수정하거나 삭제하십시오.",
    "th": "จำนวนตัวจับเวลาได้ถึงขีด จำกัด โปรดแก้ไขหรือลบตัวจับเวลาที่มีอยู่",
    "ar": "تم بلوغ الحد الأقصى للمؤقتات، عدّل أو احذف مؤقتًا موجودًا"
  },
  {
    "key": "newFirmware",
    "zh": "有新的固件版本",
    "en": "New firmware version",
    "es": "Hay una nueva versión del firmware",
    "de": "Neue Firmware-Version",
    "ja": "新ファームウェアのバージョン",
    "ru": "Есть новая версия микропрограммы",
    "fr": "Il y a une nouvelle version du firmware",
    "pt": "Existe uma nova versão de firmware",
    "uk": "Нова версія прошивки",
    "nl": "Nieuwe firmware versie",
    "ko": "새 펌웨어 버전 사용",
    "th": "มีเวอร์ชันเฟิร์มแวร์ใหม่",
    "ar": "إصدار جديد للبرنامج الثابت"
  },
  {
    "key": "upgradeImmediately",
    "zh": "立即升级",
    "en": "Upgrade immediately",
    "es": "Actualizar ahora",
    "de": "Sofort upgraden",
    "ja": "更新すぐ",
    "ru": "Немедленное обновление",
    "fr": "Mise à jour maintenant",
    "pt": "actualizar agora",
    "uk": "Оновіть негайно",
    "nl": "Onmiddellijke upgrade",
    "ko": "지금 업그레이드",
    "th": "อัพเกรดทันที",
    "ar": "حدّث الآن"
  },
  {
    "key": "Homepage",
    "zh": "返回主页",
    "en": "Homepage",
    "es": "Página principal",
    "de": "Startseite",
    "ja": "ホームページ",
    "ru": "Вернитесь на главную страницу",
    "fr": "Retour à la page d'accueil",
    "pt": "Voltar à página inicial",
    "uk": "Домашня сторінка",
    "nl": "homepage",
    "ko": "홈 페이지로 돌아가기",
    "th": "กลับสู่หน้าหลัก",
    "ar": "الصفحة الرئيسية"
  },
  {
    "key": "closeTime",
    "zh": "后关闭",
    "en": "After closing",
    "es": "Cierre posterior",
    "de": "Nach dem Schließen",
    "ja": "店を閉めた後は",
    "ru": "После закрытия",
    "fr": "Fermeture arrière",
    "pt": "Após o fecho",
    "uk": "Після закриття",
    "nl": "Na afloop",
    "ko": "후 종료",
    "th": "ปิดหลังจาก",
    "ar": "بعد الإغلاق"
  },
  {
    "key": "openTime",
    "zh": "后开启",
    "en": "After opening",
    "es": "Apertura posterior",
    "de": "Nach dem Öffnen",
    "ja": "開国後",
    "ru": "После открытия",
    "fr": "Ouverture arrière",
    "pt": "Abertura traseira",
    "uk": "Після відкриття",
    "nl": "Na opening",
    "ko": "후 오픈",
    "th": "เปิดหลังจาก",
    "ar": "بعد التشغيل"
  },
  {
    "key": "closeBLEBeforeShare",
    "zh": "分享设备前，请关闭本机蓝牙",
    "en": "Please turn off Bluetooth before sharing your device",
    "es": "Apague el Bluetooth nativo antes de compartir el dispositivo",
    "de": "Bitte schalte Bluetooth aus, bevor du dein Gerät teilst",
    "ja": "デバイスを共有する前にbluetoothをオフにしてください",
    "ru": "Перед тем как поделиться устройствами, закройте собственный Bluetooth",
    "fr": "Éteignez le Bluetooth natif avant de partager l'appareil",
    "pt": "Por favor, desligue seu Bluetooth antes de compartilhar seu dispositivo",
    "uk": "Вимкніть Bluetooth, перш ніж надавати спільний доступ до пристрою",
    "nl": "Schakel bluetooth uit voordat u het apparaat deelt",
    "ko": "장치를 공유하기 전에 네이티브 Bluetooth를 종료하십시오.",
    "th": "โปรดปิด Bluetooth ของเครื่องก่อนแชร์อุปกรณ์",
    "ar": "أوقف البلوتوث قبل مشاركة الجهاز"
  },
  {
    "key": "signal",
    "zh": "信号强度",
    "en": "Signal intensity",
    "es": "Fuerza de la señal",
    "de": "Signal Intensität",
    "ja": "信号強度",
    "ru": "Интенсивность сигнала",
    "fr": "Intensité du signal",
    "pt": "intensidade do sinal",
    "uk": "інтенсивність сигналу",
    "nl": "signaalsterkte",
    "ko": "신호 강도",
    "th": "ความเข้มของสัญญาณ",
    "ar": "قوة الإشارة"
  },
  {
    "key": "careful",
    "zh": "注意",
    "en": "Be careful",
    "es": "Atención",
    "de": "Vorsichtig sein",
    "ja": "気をつけて",
    "ru": "Внимание",
    "fr": "Attention!",
    "pt": "Tenha cuidado",
    "uk": "Будь обережний",
    "nl": "voorzichtigheid",
    "ko": "주의",
    "th": "ระวัง",
    "ar": "تنبيه"
  },
  {
    "key": "carefulTextarea",
    "zh": "蓝牙设备同一时间仅支持一台手机连接，如共享他人使用，建议在分享后先关闭本机蓝牙或本机App，等待对方连接成功后再进行其它操作。",
    "en": "Bluetooth devices only support one mobile phone connection at the same time. If sharing is used by others, it is recommended to turn off the Bluetooth or the app of the machine after sharing, and wait for the other party to connect successfully before other operations。",
    "es": "Los dispositivos Bluetooth sólo soportan una conexión de teléfono móvil al mismo tiempo, por ejemplo, para compartir el uso de otros, se recomienda que primero apague el Bluetooth nativo o la aplicación nativa después de compartir, y luego espere a que la otra parte se conecte con éxito antes de realizar otras operaciones",
    "de": "Bluetooth-Geräte unterstützen nur eine Mobiltelefonverbindung gleichzeitig. Wenn das Teilen von anderen verwendet wird, wird empfohlen, Bluetooth oder die App des Geräts nach dem Teilen auszuschalten und zu warten, bis der andere Teilnehmer erfolgreich eine Verbindung hergestellt hat, bevor andere Vorgänge ausgeführt werden",
    "ja": "bluetoothデバイスは、同時に1つの携帯電話接続をサポートします。他の人が共有する場合は、共有後にbluetoothや端末のアプリをオフにし、他の操作を行う前に相手が正常に接続するのを待つことをお勧めします",
    "ru": "Устройства Bluetooth поддерживают только одно соединение с телефоном в то же время, например, совместно используют других людей, рекомендуется закрыть собственный Bluetooth или собственный App после совместного использования, ожидая успешного подключения друг друга, а затем проводить другие операции",
    "fr": "L'appareil Bluetooth ne prend en charge qu'une seule connexion mobile en même temps. Si vous partagez avec d'autres utilisateurs, il est recommandé d'éteindre Bluetooth ou l'application locale après le partage, et d'attendre que l'autre partie se connecte avec succès avant d'effectuer d'autres opérations.",
    "pt": "Os dispositivos Bluetooth suportam apenas uma ligação de telemóvel de cada vez. Se partilhar o uso de outras pessoas, recomenda-se desligar o Bluetooth local ou a aplicação após a partilha e esperar que a outra parte se conecte com êxito antes de outras operações.",
    "uk": "Пристрої Bluetooth підтримують одночасно лише одне з'єднання мобільного телефону. Якщо спільний доступ використовується іншими, рекомендується вимкнути Bluetooth або додаток машини після спільного доступу та дочекатися успішного підключення іншої сторони перед іншими операціями",
    "nl": "Bluetooth-apparaten ondersteunen slechts een mobiele telefoonverbinding tegelijk. Als de delen worden gebruikt door anderen, wordt aanbevolen om de bluetooth of app van de machine uit te schakelen nadat de delen zijn voltooid en te wachten tot de andere persoon is verbonden voordat u andere handelingen uitvoert",
    "ko": "Bluetooth 기기는 같은 시간에 한 대의 휴대전화 연결만 지원한다. 다른 사람이 사용하는 것을 공유하는 경우 공유 후 먼저 네이티브 Bluetooth나 네이티브 App을 끄고 상대방이 연결에 성공할 때까지 기다린 뒤 다른 조작을 하는 것이 좋다.",
    "th": "อุปกรณ์ Bluetooth รองรับการเชื่อมต่อกับโทรศัพท์มือถือเพียงเครื่องเดียวในเวลาเดียวกัน หากแชร์ให้ผู้อื่นใช้ แนะนำให้ปิด Bluetooth หรือแอปของเครื่องหลังจากแชร์แล้ว รอให้ผู้อื่นเชื่อมต่อกับอุปกรณ์สำเร็จก่อนทำการดำเนินการอื่น",
    "ar": "تدعم أجهزة البلوتوث اتصال هاتف واحد فقط في الوقت نفسه. عند مشاركة الجهاز، يُنصح بإيقاف بلوتوث الهاتف أو التطبيق بعد المشاركة، ثم الانتظار حتى يتصل الطرف الآخر بنجاح قبل أي عملية أخرى."
  },
  {
    "key": "currentVersion",
    "zh": "当前版本",
    "en": "Current version",
    "es": "Versión actual",
    "de": "Aktuelle Version",
    "ja": "现行バージョン",
    "ru": "Текущая версия",
    "fr": "Version actuelle",
    "pt": "versão actual",
    "uk": "Поточна версія",
    "nl": "Huidige versie",
    "ko": "현재 버전",
    "th": "เวอร์ชันปัจจุบัน",
    "ar": "الإصدار الحالي"
  },
  {
    "key": "activationTiming",
    "zh": "激活定时",
    "en": "Activation timer",
    "es": "Tiempo de activación",
    "de": "Aktivierungszeitpunkt",
    "ja": "活性化タイミング",
    "ru": "Время активации",
    "fr": "Activer le timing",
    "pt": "Temporização da activação",
    "uk": "Терміни активації",
    "nl": "Tijd voor activering",
    "ko": "활성화 타이밍",
    "th": "ตัวจับเวลาเปิดใช้งาน",
    "ar": "تفعيل المؤقت"
  },
  {
    "key": "disableTiming",
    "zh": "禁用定时",
    "en": "Disable timer",
    "es": "Desactivar el tiempo",
    "de": "Zeitmessung deaktivieren",
    "ja": "無効タイミング",
    "ru": "Отключите время",
    "fr": "Désactiver le timing",
    "pt": "Desactivar o tempo",
    "uk": "відключення хронометражу",
    "nl": "Uitschakelen van de timing",
    "ko": "비활성화 시간",
    "th": "ปิดใช้งานตัวจับเวลา",
    "ar": "تعطيل المؤقت"
  },
  {
    "key": "turnOnDevice",
    "zh": "打开设备",
    "en": "Turn on the device",
    "es": "Abrir dispositivo",
    "de": "Schalten Sie das Gerät ein",
    "ja": "装置の電源を入れる",
    "ru": "Включите устройство",
    "fr": "Ouvrir le périphérique",
    "pt": "abrir o dispositivo",
    "uk": "включаємо пристрій",
    "nl": "Open het apparaat",
    "ko": "장치 열기",
    "th": "เปิดอุปกรณ์",
    "ar": "تشغيل الجهاز"
  },
  {
    "key": "turnOffevice",
    "zh": "关闭设备",
    "en": "Turn off the device",
    "es": "Apagar el dispositivo",
    "de": "Schalten Sie das Gerät aus",
    "ja": "装置を止める",
    "ru": "Выключить оборудование",
    "fr": "Éteignez l'appareil.",
    "pt": "Desligue o dispositivo",
    "uk": "вимкніть пристрій",
    "nl": "uitschakelapparatuur",
    "ko": "장치 종료",
    "th": "ปิดอุปกรณ์",
    "ar": "إيقاف الجهاز"
  },
  {
    "key": "microphonePermissions",
    "zh": "请打开麦克风权限",
    "en": "Please turn on microphone permissions",
    "es": "Por favor, abra los permisos del micrófono",
    "de": "Bitte aktivieren Sie die Mikrofonberechtigungen",
    "ja": "マイクの権限をオンにしてください",
    "ru": "Включите разрешения микрофона",
    "fr": "Veuillez activer les permissions du microphone",
    "pt": "Por favor, ligue a permissão do microfone",
    "uk": "Будь ласка, увімкніть дозволи мікрофона",
    "nl": "Zet de microfoontoestemming aan",
    "ko": "마이크 사용 권한을 켜십시오.",
    "th": "โปรดเปิดสิทธิ์ไมโครโฟน",
    "ar": "يرجى تفعيل إذن الميكروفون"
  },
  {
    "key": "unknown",
    "zh": "未知",
    "en": "Unknown",
    "es": "Desconocido",
    "de": "unbekannt",
    "ja": "不明",
    "ru": "Неизвестно",
    "fr": "Inconnu",
    "pt": "desconhecido",
    "uk": "невідомий",
    "nl": "onbekend",
    "ko": "알 수 없음",
    "th": "ไม่ทราบ",
    "ar": "غير معروف"
  },
  {
    "key": "clickSelect",
    "zh": "点击选择",
    "en": "Click Select",
    "es": "Haga clic para seleccionar",
    "de": "Klicken Sie auf Auswählen",
    "ja": "クリック選択",
    "ru": "Выберите щелчком мыши",
    "fr": "Cliquez sur Sélectionner",
    "pt": "Clique em Seleccionar",
    "uk": "Натисніть кнопку \"Вибрати\"",
    "nl": "Klik op selectie",
    "ko": "선택 클릭",
    "th": "คลิกเพื่อเลือก",
    "ar": "انقر للاختيار"
  },
  {
    "key": "netfail",
    "zh": "网络异常",
    "en": "Network abnormality",
    "es": "Excepción de red",
    "de": "Netzwerkanomalie",
    "ja": "ネットワーク異常",
    "ru": "Сетевые исключения",
    "fr": "Exception au réseau",
    "pt": "Excepção de rede",
    "uk": "Мережева аномалія",
    "nl": "Uitzonderingen op het netwerk",
    "ko": "네트워크 예외",
    "th": "ความผิดปกติของเครือข่าย",
    "ar": "خلل في الشبكة"
  },
  {
    "key": "microphone.Phone",
    "zh": "手机麦",
    "en": "Microphone",
    "es": "Micrófono",
    "de": "Mikrofon",
    "ja": "マイク",
    "ru": "Мобильная пшеница",
    "fr": "Mobile mai",
    "pt": "Microfone do telemóvel",
    "uk": "Мікрофон",
    "nl": "Microfoons en statieven daarvoor",
    "ko": "핸드폰 밀",
    "th": "ไมโครโฟน",
    "ar": "ميكروفون الهاتف"
  },
  {
    "key": "microphone.wai",
    "zh": "外麦",
    "en": "Device-mic",
    "es": "Dispositivo-mic",
    "de": "Geräte-Mikrofon",
    "ja": "Device-mic",
    "ru": "Внешняя пшеница",
    "fr": "Blé exotique",
    "pt": "Trigo exterior",
    "uk": "Прилад-мікрофон",
    "nl": "Device-mic",
    "ko": "겉보리",
    "th": "ไมโครโฟนอุปกรณ์",
    "ar": "ميكروفون الجهاز"
  },
  {
    "key": "galvanic_reaction",
    "zh": "通电反应",
    "en": "Galvanic reaction",
    "es": "Respuesta de potencia",
    "de": "Power-Antwort",
    "ja": "パワーレスポンス",
    "ru": "Мощность ответ",
    "fr": "Réponse de puissance",
    "pt": "Resposta de energia",
    "uk": "Реакція потужності",
    "nl": "Krachtige reactie",
    "ko": "통전 반응",
    "th": "ปฏิกิริยาไฟฟ้า",
    "ar": "استجابة الطاقة"
  },
  {
    "key": "normally_open",
    "zh": "常开",
    "en": "Normally open",
    "es": "Normalmente abierto",
    "de": "Normalerweise offen",
    "ja": "ノーマルオープン",
    "ru": "нормально открытый",
    "fr": "Normalement ouvert",
    "pt": "Normalmente aberto",
    "uk": "Нормально відкритий",
    "nl": "normaal",
    "ko": "상시",
    "th": "เปิดตามปกติ",
    "ar": "مفتوح عادةً"
  },
  {
    "key": "normally_closed",
    "zh": "常闭",
    "en": "Normally closed",
    "es": "normalmente cerrado",
    "de": "normalerweise geschlossen",
    "ja": "ノーマルクローズ",
    "ru": "нормально закрытый",
    "fr": "normalement fermé",
    "pt": "normalmente fechado",
    "uk": "нормально закритий",
    "nl": "Normaal gesloten",
    "ko": "상폐",
    "th": "ปิดตามปกติ",
    "ar": "مغلق عادةً"
  },
  {
    "key": "keep_last_time",
    "zh": "保持上一次",
    "en": "keep last time",
    "es": "mantener la última vez",
    "de": "letztes Mal behalten",
    "ja": "前回のまま",
    "ru": "держи последний раз",
    "fr": "garder la dernière fois",
    "pt": "manter última vez",
    "uk": "зберегти минулого разу",
    "nl": "Houd de laatste keer",
    "ko": "마지막으로 유지",
    "th": "เก็บครั้งสุดท้าย",
    "ar": "الاحتفاظ بآخر حالة"
  },
  {
    "key": "upgrade.prompt",
    "zh": "升级提示",
    "en": "Upgrade prompt",
    "es": "Recordatorio de actualización",
    "de": "Upgrade-Aufforderung",
    "ja": "更新プロンプト",
    "ru": "Советы по обновлению",
    "fr": "Conseils de mise à jour",
    "pt": "Dicas de actualização",
    "uk": "Запит на оновлення",
    "nl": "Tips voor het upgraden",
    "ko": "업그레이드 프롬프트",
    "th": "แจ้งเตือนการอัปเกรด",
    "ar": "تنبيه التحديث"
  },
  {
    "key": "upgrade.content",
    "zh": "有新的固件版本需要升级",
    "en": "There is a new firmware version that needs to be upgraded",
    "es": "Hay una nueva versión de firmware que debe actualizarse",
    "de": "Es gibt eine neue Firmware-Version, die aktualisiert werden muss",
    "ja": "アップグレードが必要な新しいファームウェアバージョンがあります",
    "ru": "Есть новая версия микропрограммы, которую необходимо обновить",
    "fr": "Une nouvelle version du firmware doit être mise à jour",
    "pt": "Há uma nova versão de firmware que precisa ser atualizada",
    "uk": "З'явилася нова версія прошивки, яка потребує оновлення",
    "nl": "Er zijn nieuwe firmware versies die moeten worden geupgraded",
    "ko": "업그레이드해야 할 새 펌웨어 버전",
    "th": "มีเวอร์ชันเฟิร์มแวร์ใหม่ที่ต้องอัปเกรด",
    "ar": "هناك إصدار جديد من البرنامج الثابت يحتاج إلى تحديث"
  },
  {
    "key": "upgrade",
    "zh": "升级",
    "en": "Upgrade",
    "es": "potenciar",
    "de": "Aktualisierung",
    "ja": "アップグレード",
    "ru": "Обновление",
    "fr": "Mise à jour",
    "pt": "upgrade",
    "uk": "Оновлення",
    "nl": "bevordering",
    "ko": "업그레이드",
    "th": "อัปเกรด",
    "ar": "تحديث"
  },
  {
    "key": "upgrade.cancel",
    "zh": "取消",
    "en": "Cancel",
    "es": "cancelar",
    "de": "Abbrechen",
    "ja": "キャンセル",
    "ru": "Отменено",
    "fr": "Annulation",
    "pt": "cancelar",
    "uk": "Скасувати",
    "nl": "vervallen",
    "ko": "취소",
    "th": "ยกเลิก",
    "ar": "إلغاء"
  },
  {
    "key": "nextTimeAt",
    "zh": "下一次将在",
    "en": "next time will be at",
    "es": "la próxima vez será en",
    "de": "Das nächste Mal wird um sein",
    "ja": "次回は",
    "ru": "следующий раз будет в",
    "fr": "la prochaine fois ce sera à",
    "pt": "próxima vez será em",
    "uk": "наступного разу буде о",
    "nl": "de volgende keer zal zijn",
    "ko": "다음에는",
    "th": "ครั้งถัดไปจะเป็นเวลา",
    "ar": "المرة القادمة ستكون في"
  },
  {
    "key": "year",
    "zh": "年",
    "en": "year",
    "de": "年",
    "ru": "Год",
    "fr": "Année",
    "ja": "年",
    "es": "Año",
    "pt": "ano",
    "nl": "jaar",
    "ko": "년",
    "th": "ปี",
    "ar": "سنة"
  },
  {
    "key": "month",
    "zh": "月",
    "en": "month",
    "de": "月",
    "ru": "Месяц",
    "fr": "Mois",
    "ja": "月",
    "es": "Mes",
    "pt": "mês",
    "nl": "maand",
    "ko": "월",
    "th": "เดือน",
    "ar": "شهر"
  },
  {
    "key": "th",
    "zh": "日",
    "en": "th",
    "es": "diva",
    "de": "th",
    "ja": "番目",
    "ru": "й",
    "fr": "e",
    "pt": "º",
    "uk": "тис",
    "nl": "e",
    "ko": "일",
    "th": "วันที่",
    "ar": "يوم"
  },
  {
    "key": "implement",
    "zh": "执行",
    "en": "implement",
    "es": "implementar",
    "de": "implementieren",
    "ja": "埋め込む",
    "ru": "осуществлять",
    "fr": "mettre en œuvre",
    "pt": "implemento",
    "uk": "реалізувати",
    "nl": "implementeren",
    "ko": "실행",
    "th": "ดำเนินการ",
    "ar": "تنفيذ"
  },
  {
    "key": "unopened",
    "zh": "未开启",
    "en": "Unopened",
    "es": "sin abrir",
    "de": "Ungeöffnet",
    "ja": "未開封",
    "ru": "Неоткрытый",
    "fr": "Non ouvert",
    "pt": "Fechado",
    "uk": "Нерозкритий",
    "nl": "Ongeopend",
    "ko": "켜지지 않음",
    "th": "ยังไม่เปิด",
    "ar": "غير مفتوح"
  },
  {
    "key": "turnOn",
    "zh": "开启",
    "en": "Turn on",
    "es": "encender",
    "de": "anmachen",
    "ja": "オンにする",
    "ru": "включать",
    "fr": "allumer",
    "pt": "ligar",
    "uk": "ввімкнути",
    "nl": "aanzetten",
    "ko": "오픈",
    "th": "เปิด",
    "ar": "تشغيل"
  },
  {
    "key": "turnOff",
    "zh": "关闭",
    "en": "Turn off",
    "es": "apagar",
    "de": "abschalten",
    "ja": "消す",
    "ru": "выключать",
    "fr": "éteindre",
    "pt": "desligar",
    "uk": "вимкнути",
    "nl": "uitschakelen",
    "ko": "닫기",
    "th": "ปิด",
    "ar": "إيقاف"
  },
  {
    "key": "howWork",
    "zh": "定时是怎么工作的",
    "en": "how timer works",
    "es": "cómo funciona el tiempo",
    "de": "wie Zeitmessung funktioniert",
    "ja": "タイミングの仕組み",
    "ru": "как работает тайминг",
    "fr": "comment fonctionne le chronométrage",
    "pt": "como funciona o tempo",
    "uk": "як працює час",
    "nl": "hoe timing werkt",
    "ko": "정해진 시간에 어떻게 일을 합니까?",
    "th": "วิธีการทำงานของตัวจับเวลา",
    "ar": "كيف يعمل المؤقت"
  },
  {
    "key": "loading",
    "zh": "加载中",
    "en": "Loading",
    "es": "Cargando",
    "de": "Wird geladen",
    "ja": "読み込み中",
    "ru": "Загрузка",
    "fr": "Chargement",
    "pt": "Carregando",
    "uk": "Завантаження",
    "nl": "Bezig met laden",
    "ko": "로드 중",
    "th": "กำลังโหลด",
    "ar": "جارٍ التحميل"
  },
  {
    "key": "add_cycle_timing",
    "zh": "添加周期定时",
    "en": "Add cycle timer",
    "es": "Agregar tiempo de ciclo",
    "de": "Zykluszeit hinzufügen",
    "ja": "サイクルタイミングを追加",
    "ru": "Добавьте время цикла",
    "fr": "Ajouter une durée de cycle",
    "pt": "Adicionar tempo de ciclo",
    "uk": "Додати час циклу",
    "nl": "Voeg cyclustiming toe",
    "ko": "주기 시간 추가",
    "th": "เพิ่มตัวจับเวลาวงรอบ",
    "ar": "إضافة مؤقت دوري"
  },
  {
    "key": "request_error",
    "zh": "请求错误",
    "en": "Request error",
    "es": "Error de solicitud",
    "de": "Anforderungsfehler",
    "ja": "リクエストエラー",
    "ru": "Ошибка запроса",
    "fr": "Erreur de requête",
    "pt": "Erro de solicitação",
    "uk": "Помилка запиту",
    "nl": "Verzoekfout",
    "ko": "요청 오류",
    "th": "ข้อผิดพลาดของคำขอ",
    "ar": "خطأ في الطلب"
  },
  {
    "key": "switchlog",
    "zh": "开关日志",
    "en": "Switch log",
    "es": "Registro de interruptores",
    "de": "Protokoll wechseln",
    "ja": "スイッチログ",
    "ru": "Журнал выключателей",
    "fr": "Journal des commutateurs",
    "pt": "Alternar registo",
    "uk": "Змінення журналу",
    "nl": "Schakellogboek",
    "ko": "스위치 로그",
    "th": "บันทึกสวิตช์",
    "ar": "سجل التشغيل"
  },
  {
    "key": "noData",
    "zh": "暂无数据",
    "en": "No data available",
    "es": "Sin datos disponibles",
    "de": "Keine Daten verfügbar",
    "ja": "データがありません",
    "ru": "Нет доступных данных",
    "fr": "Aucune donnée disponible",
    "pt": "Nenhum dado disponível",
    "uk": "Даних немає",
    "nl": "Geen gegevens beschikbaar",
    "ko": "데이터가 없습니다",
    "th": "ไม่มีข้อมูล",
    "ar": "لا توجد بيانات"
  },
  {
    "key": "setUp",
    "zh": "设置",
    "en": "Setting",
    "es": "Configuración",
    "de": "Einstellungen",
    "ja": "設定",
    "ru": "Настройки",
    "fr": "Paramètres",
    "pt": "Configurações",
    "uk": "Налаштування",
    "nl": "Instellingen",
    "ko": "설정",
    "th": "การตั้งค่า",
    "ar": "الإعدادات"
  },
  {
    "key": "footer.CalibrationLineSequence",
    "zh": "颜色校准",
    "en": "Calibration",
    "es": "Calibración",
    "de": "Kalibrierung",
    "ja": "較正",
    "ru": "Калибровка цвета",
    "fr": "Calibrage des couleurs",
    "pt": "Calibração",
    "uk": "Калібрування",
    "nl": "ijking",
    "ko": "지정",
    "th": "การปรับเทียบ",
    "ar": "معايرة"
  },
  {
    "key": "modal.nextStep",
    "zh": "下一步",
    "en": "Next",
    "es": "Siguiente paso",
    "de": "Nächster Schritt",
    "ja": "次のステップ",
    "ru": "Далее",
    "fr": "L'étape suivante",
    "pt": "Próximo passo",
    "uk": "Наступний крок",
    "nl": "Volgende stap",
    "ko": "다음 단계",
    "th": "ถัดไป",
    "ar": "التالي"
  },
  {
    "key": "modal.chooseLedColor",
    "zh": "请选择灯条当前显示颜色",
    "en": "Please Choose Led Color",
    "es": "Seleccione el color LED",
    "de": "Bitte wählen Sie LED-Farbe",
    "ja": "ledの色をお選びください",
    "ru": "Выберите текущий цвет отображения лампы",
    "fr": "Veuillez sélectionner la couleur d'affichage actuelle de la barre lumineuse",
    "pt": "Por favor, escolha a Cor do Guiado",
    "uk": "Будь ласка, виберіть світлодіодний колір",
    "nl": "Gelieve de kleur van de Led te kiezen",
    "ko": "Led 색상을 선택하십시오.",
    "th": "กรุณาเลือกสีของ LED",
    "ar": "يرجى اختيار لون LED"
  },
  {
    "key": "RGBTurnModal.red",
    "zh": "红色",
    "en": "Red",
    "es": "Rojo",
    "de": "Rot",
    "ja": "赤い",
    "ru": "Красный",
    "fr": "Rouge",
    "pt": "Vermelho.",
    "uk": "Червоний",
    "nl": "rood",
    "ko": "빨강",
    "th": "สีแดง",
    "ar": "أحمر"
  },
  {
    "key": "RGBTurnModal.green",
    "zh": "绿色",
    "en": "Green",
    "es": "Verde",
    "de": "Grün",
    "ja": "グリーン",
    "ru": "Зеленый цвет",
    "fr": "Vert",
    "pt": "Verde.",
    "uk": "Зелений",
    "nl": "nl",
    "ko": "그린",
    "th": "สีเขียว",
    "ar": "أخضر"
  },
  {
    "key": "RGBTurnModal.blue",
    "zh": "蓝色",
    "en": "Blue",
    "es": "Azul",
    "de": "Blau",
    "ja": "青い",
    "ru": "Синий цвет",
    "fr": "Bleu",
    "pt": "Azul.",
    "uk": "Синій",
    "nl": "blauw",
    "ko": "파란색",
    "th": "สีน้ำเงิน",
    "ar": "أزرق"
  },
  {
    "key": "update_app",
    "zh": "请更新app",
    "en": "Please update the app",
    "es": "Por favor, actualice la aplicación",
    "de": "Bitte aktualisieren Sie die App",
    "ja": "アプリを更新してください",
    "ru": "Пожалуйста, обновите приложение",
    "fr": "Veuillez mettre à jour l'application",
    "pt": "Por favor, atualize o aplicativo",
    "uk": "Будь ласка, оновіть додаток",
    "nl": "Werk de app bij",
    "ko": "앱을 업데이트하십시오",
    "th": "กรุณาอัปเดตแอป",
    "ar": "يرجى تحديث التطبيق"
  },
  {
    "key": "please_wait",
    "zh": "请等待",
    "en": "Please wait",
    "es": "Por favor espera",
    "de": "Bitte warten",
    "ja": "お待ちください",
    "ru": "Пожалуйста, подождите",
    "fr": "Veuillez patienter",
    "pt": "Por favor, aguarde",
    "uk": "Будь ласка, зачекайте",
    "nl": "Even geduld alstublieft",
    "ko": "잠시만 기다려주세요",
    "th": "กรุณารอสักครู่",
    "vi": "Vui lòng đợi",
    "ar": "يرجى الانتظار"
  },
  {
    "key": "input_error",
    "zh": "输入错误",
    "en": "Input error",
    "es": "Error de entrada",
    "de": "Eingabefehler",
    "ja": "入力エラー",
    "ru": "Ошибка ввода",
    "fr": "Erreur de saisie",
    "pt": "Erro de entrada",
    "uk": "Помилка введення",
    "nl": "Invoerfout",
    "ko": "입력 오류",
    "th": "ข้อผิดพลาดในการป้อนข้อมูล",
    "vi": "Lỗi nhập liệu",
    "ar": "خطأ في الإدخال"
  }
];
